name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-12
    steps:

      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: heiher/hev-socks5-tunnel
          path: 'tun'

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Dependencies
        run: |
          command -v "brew" >/dev/null 2>&1 || {
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          }
          brew install libyaml 
          
      - name: Build xcframework
        run: |
          cd tun
          ./build.sh
          zip -ry ./HevSocks5Tunnel.xcframework.zip ./HevSocks5Tunnel.xcframework
          
      - name: Render Template
        run: |
          export TEMP=`shasum -a 256 tun/HevSocks5Tunnel.xcframework.zip`
          export CHECKSUM=${TEMP:0:64}
          cd Templates
          sed -i "_bak" "s/VERSION/${{ github.event.inputs.version }}/g" Package.template
          sed -i "_bak" "s/CHECKSUM/${CHECKSUM}/g" Package.template
          
      - name: Update Package.swift
        run: |
          rm -f Package.swift
          cp ./Templates/Package.template Package.swift
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: T2SApple Release ${{ github.event.inputs.version }}!!!
          commit_user_name: GFWFighter
          commit_user_email: gfwfightingsoldier@gmail.com
          tagging_message: ${{ github.event.inputs.version }}
          file_pattern: 'Package.swift'
          
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          files: tun/HevSocks5Tunnel.xcframework.zip
